name: starguide_server
description: Starting point for a Serverpod server.

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.3.0
  dartantic_ai: ^0.9.7
  serverpod: ^2.8.0

dev_dependencies:
  lints: ^6.0.0
  test: "^1.24.2"
  serverpod_test: ^2.8.0
