name: starguide_flutter
description: A new Flutter project with Serverpod.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.3.1
  flutter_chat_ui: ^2.3.1
  flyer_chat_text_message: ^2.2.1
  gpt_markdown: ^1.0.19
  made_with_serverpod: ^1.1.0
  serverpod_flutter: ^2.8.0
  starguide_client:
    path: ../starguide_client
  syntax_highlight: ^0.4.0
  provider: ^6.1.4
  uuid: ^4.5.1
  cupertino_icons: ^1.0.5
  g_recaptcha_v3: ^1.0.0

dev_dependencies:
  flutter_lints: ">=3.0.0 <6.0.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
